-- =========================================================================
-- e-politica.ia - Production Database Schema (Supabase Postgres + RLS)
-- Applied as migration `initial_schema_auth_rls` on project tlnprjkiydiogrcsruxw
-- =========================================================================

-- 1. Profiles (auto-created on signup)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  email TEXT,
  title TEXT DEFAULT 'Assinante',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)), NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END; $$;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. Per-user application state (campaign params, CRM, tasks, payment)
CREATE TABLE IF NOT EXISTS public.user_state (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  campaign_params JSONB,
  contacts JSONB,
  tasks JSONB,
  payment_status JSONB,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.user_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_state_select_own" ON public.user_state FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_state_insert_own" ON public.user_state FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_state_update_own" ON public.user_state FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "user_state_delete_own" ON public.user_state FOR DELETE USING (auth.uid() = user_id);

-- 3. Payments ledger (written only by service role via webhook)
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  email TEXT,
  provider TEXT NOT NULL DEFAULT 'mercadopago',
  provider_payment_id TEXT,
  amount NUMERIC(10,2),
  currency TEXT DEFAULT 'BRL',
  status TEXT NOT NULL DEFAULT 'pending',
  raw JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "payments_select_own" ON public.payments FOR SELECT USING (auth.uid() = user_id);

-- 4. Shared electoral reference data (read-only for clients)
CREATE TABLE IF NOT EXISTS public.candidates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  party TEXT NOT NULL,
  role TEXT NOT NULL,
  avatar TEXT,
  color TEXT,
  status TEXT,
  base_count INTEGER DEFAULT 0,
  target_goal INTEGER DEFAULT 10000,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.regions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  population INTEGER NOT NULL,
  profile TEXT,
  issues TEXT,
  map_x NUMERIC NOT NULL,
  map_y NUMERIC NOT NULL,
  color_strength NUMERIC DEFAULT 0.5,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.voting_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  candidate_id TEXT REFERENCES public.candidates(id),
  votes INTEGER NOT NULL,
  percentage NUMERIC NOT NULL,
  region_id TEXT REFERENCES public.regions(id),
  zone_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voting_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "candidates_read_all" ON public.candidates FOR SELECT USING (true);
CREATE POLICY "regions_read_all" ON public.regions FOR SELECT USING (true);
CREATE POLICY "voting_results_read_all" ON public.voting_results FOR SELECT USING (true);

-- Seed reference data
INSERT INTO public.candidates (id, name, party, role, avatar, color, status, base_count, target_goal) VALUES
('dr-marcos-silva', 'Dr. Marcos Silva', 'PSD (12)', 'Prefeito', '👨‍⚕️', 'var(--accent-green)', 'Candidato Principal', 7420, 10000),
('ana-souza', 'Ana Souza', 'PL (22)', 'Prefeito', '👩‍💼', 'var(--accent-blue)', 'Concorrente 1', 6850, 9500),
('roberto-lima', 'Roberto Lima', 'PT (13)', 'Prefeito', '👨‍💼', 'var(--accent-yellow)', 'Concorrente 2', 5120, 8000)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.regions (id, name, population, profile, issues, map_x, map_y, color_strength) VALUES
('centro', 'Centro', 45000, 'Comercial e residencial médio-alto', 'Segurança e trânsito', 50, 50, 0.8),
('vila-nova', 'Vila Nova', 32000, 'Residencial familiar popular', 'Saneamento e postos de saúde', 30, 35, 0.95),
('jardins', 'Jardins', 28000, 'Alto padrão residencial', 'Iluminação e conservação de praças', 70, 30, 0.4),
('floresta', 'Floresta', 38000, 'Zona mista residencial e verde', 'Transporte público e creches', 35, 65, 0.65),
('industrial', 'Distrito Industrial', 15000, 'Operário e industrial', 'Asfalto de vias pesadas e poluição', 65, 70, 0.75),
('morada-sol', 'Morada do Sol', 22000, 'Expansão urbana recente', 'Escolas e internet de alta velocidade', 80, 55, 0.85)
ON CONFLICT (id) DO NOTHING;

-- Security hardening: the trigger function must not be callable via the API
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
