-- =========================================================================
-- e-politica.ia - Production Database Schema (PostgreSQL for Supabase)
-- =========================================================================

-- 1. Candidates registry
CREATE TABLE IF NOT EXISTS candidates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    party TEXT NOT NULL,
    role TEXT NOT NULL,
    avatar TEXT,
    color TEXT,
    status TEXT,
    base_count INTEGER DEFAULT 0,
    target_goal INTEGER DEFAULT 10000,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Geographic regions / neighborhoods
CREATE TABLE IF NOT EXISTS regions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    population INTEGER NOT NULL,
    profile TEXT,
    issues TEXT,
    map_x NUMERIC NOT NULL,
    map_y NUMERIC NOT NULL,
    color_strength NUMERIC DEFAULT 0.5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. CRM Contacts base (Voters, Leaders, Volunteers)
CREATE TABLE IF NOT EXISTS crm_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Apoiador', 'Liderança', 'Voluntário', 'Eleitor')),
    phone TEXT NOT NULL,
    email TEXT,
    zone TEXT NOT NULL,
    region_id TEXT REFERENCES regions(id),
    region_name TEXT NOT NULL,
    status TEXT DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Pendente', 'Inativo')),
    subscribers INTEGER DEFAULT 0,
    last_contact DATE DEFAULT CURRENT_DATE,
    notes TEXT,
    map_x NUMERIC NOT NULL,
    map_y NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Campaign Todo Tasks
CREATE TABLE IF NOT EXISTS campaign_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    done BOOLEAN DEFAULT FALSE,
    priority TEXT DEFAULT 'media' CHECK (priority IN ('alta', 'media', 'baixa')),
    page TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Historical election voting results
CREATE TABLE IF NOT EXISTS voting_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    candidate_id TEXT REFERENCES candidates(id),
    votes INTEGER NOT NULL,
    percentage NUMERIC NOT NULL,
    region_id TEXT REFERENCES regions(id),
    zone_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- Initial Mock Data Population
-- =========================================================================

-- Insert Candidates
INSERT INTO candidates (id, name, party, role, avatar, color, status, base_count, target_goal) VALUES
('dr-marcos-silva', 'Dr. Marcos Silva', 'PSD (12)', 'Prefeito', '👨‍⚕️', 'var(--accent-green)', 'Candidato Principal', 7420, 10000),
('ana-souza', 'Ana Souza', 'PL (22)', 'Prefeito', '👩‍💼', 'var(--accent-blue)', 'Concorrente 1', 6850, 9500),
('roberto-lima', 'Roberto Lima', 'PT (13)', 'Prefeito', '👨‍💼', 'var(--accent-yellow)', 'Concorrente 2', 5120, 8000)
ON CONFLICT (id) DO NOTHING;

-- Insert Regions
INSERT INTO regions (id, name, population, profile, issues, map_x, map_y, color_strength) VALUES
('centro', 'Centro', 45000, 'Comercial e residencial médio-alto', 'Segurança e trânsito', 50, 50, 0.8),
('vila-nova', 'Vila Nova', 32000, 'Residencial familiar popular', 'Saneamento e postos de saúde', 30, 35, 0.95),
('jardins', 'Jardins', 28000, 'Alto padrão residencial', 'Iluminação e conservação de praças', 70, 30, 0.4),
('floresta', 'Floresta', 38000, 'Zona mista residencial e verde', 'Transporte público e creches', 35, 65, 0.65),
('industrial', 'Distrito Industrial', 15000, 'Operário e industrial', 'Asfalto de vias pesadas e poluição', 65, 70, 0.75),
('morada-sol', 'Morada do Sol', 22000, 'Expansão urbana recente', 'Escolas e internet de alta velocidade', 80, 55, 0.85)
ON CONFLICT (id) DO NOTHING;

-- Insert Tasks
INSERT INTO campaign_tasks (text, done, priority, page) VALUES
('Reunião de alinhamento com Clara Mendes (Jardins)', true, 'alta', 'CRM'),
('Revisar relatório eleitoral da Zona 12 com marqueteiro', false, 'alta', 'Analytics'),
('Distribuir materiais de panfletagem para Felipe Santos', false, 'media', 'CRM'),
('Fazer simulação de plano de ação na IA Poliana sobre Segurança', false, 'media', 'Assistant'),
('Verificar lideranças inativas no distrito industrial', true, 'baixa', 'CRM'),
('Exportar PDF analítico do comparativo de candidatos', false, 'baixa', 'Comparison');

-- Insert CRM Mapped Contacts
INSERT INTO crm_contacts (name, role, phone, email, zone, region_id, region_name, status, subscribers, notes, map_x, map_y) VALUES
('Reginaldo de Souza', 'Liderança', '(11) 98765-4321', 'reginaldo.souza@gmail.com', 'Zona 12', 'vila-nova', 'Vila Nova', 'Ativo', 245, 'Grande líder de associação de moradores. Organizou evento com 80 pessoas semana passada.', 28, 33),
('Dr. Roberto Antunes', 'Apoiador', '(11) 98123-4567', 'dr.antunes.med@hotmail.com', 'Zona 12', 'centro', 'Centro', 'Ativo', 42, 'Apoia no setor de saúde pública. Influente entre médicos locais.', 52, 48),
('Clara Maria Mendes', 'Liderança', '(11) 97542-1298', 'clara.mendes.jardins@outlook.com', 'Zona 56', 'jardins', 'Jardins', 'Ativo', 180, 'Coordena o grupo de mulheres empreendedoras. Muito ativa nas redes sociais.', 72, 28),
('Felipe Silva Santos', 'Voluntário', '(11) 99654-8732', 'felipe.santos.vol@gmail.com', 'Zona 34', 'floresta', 'Floresta', 'Ativo', 15, 'Disponível para panfletagem de rua e organização de comitês.', 38, 62),
('Mariana Costa Ramos', 'Liderança', '(11) 96321-7890', 'mariana.industrial@yahoo.com.br', 'Zona 56', 'industrial', 'Distrito Industrial', 'Ativo', 310, 'Líder sindical e coordenadora de base metalúrgica. Extremamente influente.', 68, 68),
('José Augusto (Zezinho)', 'Voluntário', '(11) 97410-8523', 'zezinho.morada@gmail.com', 'Zona 34', 'morada-sol', 'Morada do Sol', 'Pendente', 8, 'Interessado em apoiar no som móvel e distribuição de cartazes.', 82, 53),
('Sandra Mara Pereira', 'Eleitor', '(11) 98522-3698', 'sandra.mara.centro@gmail.com', 'Zona 12', 'centro', 'Centro', 'Ativo', 0, 'Dona de comércio local. Prometeu colocar adesivos na vitrine.', 47, 53),
('Carlos Eduardo Gouveia', 'Apoiador', '(11) 99823-1122', 'cadu.gouveia@gmail.com', 'Zona 34', 'vila-nova', 'Vila Nova', 'Inativo', 50, 'Precisa de contato de reativação. Estava insatisfeito com agenda antiga.', 32, 38);
